# This is a basic workflow to help you get started with Actions

name: CI For Cloud-Native Toolkit Private Catalog

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ubuntu:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup
        run: |
          apt-get update
          apt-get install -y git
          apt-get clean

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Build Source
        run: ./scripts/build.sh

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

        # Runs a single command using the runners shell
      - name: Install release-it
        run: npm i -g release-it

      - name: Publish
        run: release-it --ci --no-npm minor --verbose -VV -c .release-it.yaml
        env:
          GITHUB_TOKEN: ${{ github.token }}